version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    groups:
      cargo-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      cargo-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"
