[package]
name = "dolos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
tree-sitter = "=0.26.6"
tree-sitter-java = "=0.23.5"
tree-sitter-c = "0.24.1"
tree-sitter-javascript = "=0.25.0"
tree-sitter-python = "=0.25"
tree-sitter-language = "0.1.7"

[dev-dependencies]
serde_any = "0.5"
rand = "0.10.1"