pub type Hash = usize;

/// The modulus used in the hash calculations.
///
/// Since we want to be able to take the product of two hashes, the product of
/// two hashes, the modulus multiplied by itself should not have more than the
/// available amount of bits of precision.
///
/// Javascript has 53-bit precision numbers (doubles) so we pick the largest
/// prime number with 26 bits.
const MOD: u64 = 33554393;

/// The base (or radix) used in the hash calculation for rolling hashes.
///
/// The hashes/numbers generated by token_hash should already use as much
/// bits as possible because they share the same modulus.
///
/// We have chosen for the largest prime with 22 bits.
const BASE_ROLLING: u64 = 4194301;

/// The base (or radix) used in the hash calculation for token hashes.
///
/// We want that even small tokens use as much bits as possible. Because we
/// assume the input token characters will mostly be less than 128, we pick
/// our base such that multiplying with an input character use as much bits
/// as possible.
///
/// Hence this is the largest prime number such that 127 * BASE_TOKEN < MOD.
const BASE_TOKEN: u64 = 747287;

/// Implementation of a rolling hash function.
///
/// This should be an equivalent implementation of the npm @dodona/dolos-lib
/// package's hashing function. Because of this, the hashes do not use the full
/// range provided by 64-bit numbers.
///
/// The arithmetic below is done in `u64` even though the resulting hashes
/// (bounded by `MOD`, ~2^25) fit in 32 bits: the intermediate products (e.g.
/// `BASE_ROLLING * hash`) reach ~2^47-2^50 and would silently overflow a
/// 32-bit `usize` on targets like `wasm32`.
pub struct RollingHash {
    k: usize,
    max_base: u64,
    memory: Vec<u64>,
    i: usize,
    hash: u64,
}

impl RollingHash {
    pub fn new(k: usize) -> Self {
        RollingHash {
            k,
            max_base: MOD - mod_exp(BASE_ROLLING, k as u64, MOD),
            memory: vec![0; k],
            i: 0,
            hash: 0,
        }
    }

    /// Adds a token to the rolling hash and calculates the new hash value.
    pub fn next_hash(&mut self, token: usize) -> Hash {
        let token = token as u64;
        self.hash = (BASE_ROLLING * self.hash + token + self.max_base * self.memory[self.i]) % MOD;
        self.memory[self.i] = token;
        self.i = (self.i + 1) % self.k;
        self.hash as Hash
    }
}

/// Creates a quick hash of a string (token)
pub fn hash_token(token: &str) -> Hash {
    token
        .bytes()
        .fold(0u64, |hash, byte| ((hash + byte as u64) * BASE_TOKEN) % MOD) as Hash
}

/// Modular exponentation without overflowing.
///
/// Code based on the pseudocode at <https://en.wikipedia.org/wiki/Modular_exponentiation#Pseudocode>.
const fn mod_exp(base: u64, exp: u64, modulus: u64) -> u64 {
    let mut y = 1;
    let mut b = base;
    let mut e = exp;
    while e > 1 {
        if e % 2 == 1 {
            y = (b * y) % modulus;
        }
        b = (b * b) % modulus;
        e >>= 1;
    }
    (b * y) % modulus
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::winnowing::tokenizer::Token;

    // These tests generally test whether the hashes generated by this implementation match with
    // those from the original Dolos implementation.

    #[test]
    fn test_mod_exp() {
        assert_eq!(mod_exp(4, 13, 497), 445);
    }

    #[test]
    fn test_hash_tokens() {
        let tokens: Vec<Token> = serde_any::from_file("fixtures/sample.tokens.json").unwrap();
        let hashes: Vec<usize> = serde_any::from_file("fixtures/sample.hashes.json").unwrap();
        let token_names = tokens
            .iter()
            .map(|t| t.name.clone())
            .collect::<Vec<String>>();

        for i in 0..tokens.len() {
            assert_eq!(
                hash_token(&token_names[i]),
                hashes[i],
                "Mismatch for '{}'",
                token_names[i]
            );
        }
    }

    #[test]
    fn test_rolling_hash() {
        let tokens: Vec<Token> = serde_any::from_file("fixtures/sample.tokens.json").unwrap();
        let token_hashes: Vec<usize> = serde_any::from_file("fixtures/sample.hashes.json").unwrap();

        for k in [3, 17] {
            let rolling_hashes: Vec<usize> =
                serde_any::from_file(format!("fixtures/sample.rolling{}.json", k)).unwrap();
            let mut hasher = RollingHash::new(k);

            for i in 0..tokens.len() {
                assert_eq!(
                    hasher.next_hash(token_hashes[i]),
                    rolling_hashes[i],
                    "Mismatch at k={} for '{}'",
                    k,
                    tokens[i].name
                );
            }
        }
    }
}
