type Hash = usize;

/// The modulus used in the hash calculations.
///
/// Since we want to be able to take the product of two hashes, the product of
/// two hashes, the modulus multiplied by itself should not have more than the
/// available amount of bits of precision.
///
/// Javascript has 53-bit precision numbers (doubles) so we pick the largest
/// prime number with 26 bits.
const MOD: usize = 33554393;

/// The base (or radix) used in the hash calculation for rolling hashes.
///
/// The hashes/numbers generated by token_hash should already use as much
/// bits as possible because they share the same modulus.
///
/// We have chosen for the largest prime with 22 bits.
const BASE_ROLLING: usize = 4194301;

/// The base (or radix) used in the hash calculation for token hashes.
///
/// We want that even small tokens use as much bits as possible. Because we
/// assume the input token characters will mostly be less than 128, we pick
/// our base such that multiplying with an input character use as much bits
/// as possible.
///
/// Hence this is the largest prime number such that 127 * BASE_TOKEN < MOD.
const BASE_TOKEN: usize = 747287;

/// Implementation of a rolling hash function.
///
/// This should be an equivalent implementation of the npm @dodona/dolos-lib
/// package's hashing function. Because of this, the hashes do not use the full
/// range provided by 64-bit usize numbers.
pub struct RollingHash {
    k: usize,
    max_base: usize,
    memory: Vec<usize>,
    i: usize,
    hash: usize,
}

impl RollingHash {
    pub fn new(k: usize) -> Self {
        RollingHash {
            k,
            max_base: MOD - mod_exp(BASE_ROLLING, k, MOD),
            memory: vec![0; k],
            i: 0,
            hash: 0,
        }
    }

    /// Adds a token to the rolling hash and calculates the new hash value.
    pub fn next_hash(&mut self, token: usize) -> Hash {
        self.hash = (BASE_ROLLING * self.hash + token + self.max_base * self.memory[self.i]) % MOD;
        self.memory[self.i] = token;
        self.i = (self.i + 1) % self.k;
        self.hash
    }
}

/// Creates a quick hash of a string (token)
pub fn hash_token(token: &str) -> Hash {
    dbg!(token);
    token
        .bytes()
        .fold(0, |hash, byte| ((hash + byte as usize) * BASE_TOKEN) % MOD)
}

/// Modular exponentation without overflowing.
///
/// Code based on the pseudocode at <https://en.wikipedia.org/wiki/Modular_exponentiation#Pseudocode>.
const fn mod_exp(base: usize, exp: usize, modulus: usize) -> usize {
    let mut y = 1;
    let mut b = base;
    let mut e = exp;
    while e > 1 {
        if e % 2 == 1 {
            y = (b * y) % modulus;
        }
        b = (b * b) % modulus;
        e >>= 1;
    }
    return (b * y) % modulus;
}

#[cfg(test)]
mod tests {
    extern crate serde;
    extern crate serde_any;

    use super::*;

    // These tests generally test whether the hashes generated by this implementation match with
    // those from the original Dolos implementation.

    #[test]
    fn test_mod_exp() {
        assert_eq!(mod_exp(4, 13, 497), 445);
    }

    #[test]
    fn test_hash_tokens() {
        let tokens: Vec<String> = serde_any::from_file("fixtures/sample.tokens.json").unwrap();
        let hashes: Vec<usize> = serde_any::from_file("fixtures/sample.hashes.json").unwrap();

        for i in 0..tokens.len() {
            assert_eq!(
                hash_token(&tokens[i]),
                hashes[i],
                "Mismatch for '{}'",
                tokens[i]
            );
        }
    }

    #[test]
    fn test_rolling_hash_k3() {
        let tokens: Vec<String> = serde_any::from_file("fixtures/sample.tokens.json").unwrap();
        let token_hashes: Vec<usize> = serde_any::from_file("fixtures/sample.hashes.json").unwrap();
        let rolling_hashes: Vec<usize> =
            serde_any::from_file("fixtures/sample.rolling3.json").unwrap();
        let mut hasher = RollingHash::new(3);

        for i in 0..tokens.len() {
            assert_eq!(
                hasher.next_hash(token_hashes[i]),
                rolling_hashes[i],
                "Mismatch for '{}'",
                tokens[i]
            );
        }
    }

    #[test]
    fn test_rolling_hash_k17() {
        let tokens: Vec<String> = serde_any::from_file("fixtures/sample.tokens.json").unwrap();
        let token_hashes: Vec<usize> = serde_any::from_file("fixtures/sample.hashes.json").unwrap();
        let rolling_hashes: Vec<usize> =
            serde_any::from_file("fixtures/sample.rolling17.json").unwrap();
        let mut hasher = RollingHash::new(17);

        for i in 0..tokens.len() {
            assert_eq!(
                hasher.next_hash(token_hashes[i]),
                rolling_hashes[i],
                "Mismatch for '{}'",
                tokens[i]
            );
        }
    }
}
